tc3262: fix build regression on rt6xxx
arch/mips/tc3262/irq.c: In function 'tc_bus_timeout_interrupt':
arch/mips/tc3262/irq.c:299:15: error: unused variable 'reg' [-Werror=unused-variable]
  unsigned int reg = READ_ONCE(VPint(CR_PRATIR));
               ^~~
cc1: all warnings being treated as errors